<?php
return array (
  'autogenerated-1-c4ca4238a0b923820dcc509a6f75849b' => 
  array (
    'base' => 'https://typo3.ddev.site:4443/',
    'dependencies' => 
    array (
      0 => 'htl3r/typo3-demo',
      1 => 'bootstrap-package/full',
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'en_US.UTF-8',
        'navigationTitle' => 'English',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 1,
    'websiteTitle' => '',
  ),
);
#